### ISSUE TITLE
TOC navigation doesn't work with firefox

### ISSUE THREAD

**Issue by ghost** [laobubu/jekyll-theme-EasyBook#3] opened 2016-03-16 05:40 UTC
Navigation with TOC is not working with firefox. It works well with chrome.
If I start the server locally, then it works with firefox also. I am not expert in this area, but appears like some js security features disabling it for firefox. You may also confirm this with demo site + firefox.

**Comment by laobubu** [comment] 2016-03-16 06:18
Confirmed. Working on it.

**Comment by laobubu** [comment] 2016-03-16 06:38
The reason is that Chrome uses `document.body.scrollTop` to get or set the scroll position, which FireFox doesn't support. Now fixed.

**Closed as completed** 2016-03-16 06:38 UTC
Labels: bug
